language: node_js

node_js:
  - "8.5"

services:
  - postgresql

addons:
  postgresql: "9.6"

sudo: false
dist: trusty

before_script:
  - echo 'Europe/London' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
  - lerna bootstrap

before_install:
  - export TZ=Europe/London

env:
  global:
    - PG_CONNECTION_STRING=postgres://postgres:postgres@localhost:5432
    - DEBUG=*,-mocha:runner,-mocha:runnable,-mocha:suite,-eslint:config,-eslint:config-ops,-eslint:cli-engine,-eslint:glob-util,-eslint:config-file,-eslint:code-path
    - TIMEOUT=15000
    - DEBUG_COLORS=false

webhooks:
  - https://outlook.office.com/webhook/b88897d4-c48a-4fe2-9097-7c761e69ce94@c8b125d0-ba85-4441-8b06-df523851b190/TravisCI/c969c9d2046a4d9cb8cae895080fe3fa/55765507-4a3a-4ed3-b79b-7ddb4ff8b759

after_success:
  - "npm i codecov"
  - istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec ./plugins/tymly-alerts-plugin/test
  - bash <(curl -s https://codecov.io/bash) -cF alerts_plugin
  - istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec ./plugins/tymly-etl-plugin/test
  - bash <(curl -s https://codecov.io/bash) -cF etl_plugin
  - istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec ./plugins/tymly-express-plugin/test
  - bash <(curl -s https://codecov.io/bash) -cF express_plugin
  - istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec ./plugins/tymly-forms-plugin/test
  - bash <(curl -s https://codecov.io/bash) -cF forms_plugin
  - istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec ./plugins/tymly-pg-plugin/test
  - bash <(curl -s https://codecov.io/bash) -cF pg_plugin
  - istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec ./plugins/tymly-rankings-plugin/test
  - bash <(curl -s https://codecov.io/bash) -cF rankings_plugin
  - istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec ./plugins/tymly-solr-plugin/test
  - bash <(curl -s https://codecov.io/bash) -cF solr_plugin
  - istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec ./plugins/tymly-users-plugin/test
  - bash <(curl -s https://codecov.io/bash) -cF users_plugin
  - istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec ./packages/address-matcher/test
  - bash <(curl -s https://codecov.io/bash) -cF addressmatcher
  - istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec ./packages/asl-choice-processor/test
  - bash <(curl -s https://codecov.io/bash) -cF asl
  - istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec ./packages/form-maker/test
  - bash <(curl -s https://codecov.io/bash) -cF form_maker
  - istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec ./packages/hl-pg-client/test
  - bash <(curl -s https://codecov.io/bash) -cF hl_pg_client
  - istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec ./packages/pg-concat/test
  - bash <(curl -s https://codecov.io/bash) -cF pg_concat
  - istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec ./packages/pg-delta-file/test
  - bash <(curl -s https://codecov.io/bash) -cF pg_delta_file
  - istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec ./packages/pg-diff-sync/test
  - bash <(curl -s https://codecov.io/bash) -cF pg_diff_sync
  - istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec ./packages/pg-info/test
  - bash <(curl -s https://codecov.io/bash) -cF pg_info
  - istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec ./packages/pg-model/test
  - bash <(curl -s https://codecov.io/bash) -cF pg_model
  - istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec ./packages/pg-telepods/test
  - bash <(curl -s https://codecov.io/bash) -cF pg_teleopds
  - istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec ./packages/relationize/test
  - bash <(curl -s https://codecov.io/bash) -cF relationize
  - istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec ./packages/smithereens/test
  - bash <(curl -s https://codecov.io/bash) -cF smithereens
  - istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec ./packages/statebox/test
  - bash <(curl -s https://codecov.io/bash) -cF statebox
  - istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec ./packages/supercopy/test
  - bash <(curl -s https://codecov.io/bash) -cF supercopy
  - istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec ./packages/tymly/test
  - bash <(curl -s https://codecov.io/bash) -cF tymly
  - istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec ./packages/xml2csv/test
  - bash <(curl -s https://codecov.io/bash) -cF xml2csv