language: node_js

node_js:
  - "8.5"

services:
  - postgresql

addons:
  postgresql: "9.6"

sudo: false
dist: trusty

before_script:
  - lerna bootstrap

env:
  global:
    - PG_CONNECTION_STRING=postgres://postgres:postgres@localhost:5432
    - DEBUG=*,-mocha:runner,-mocha:runnable,-mocha:suite,-eslint:config,-eslint:config-ops,-eslint:cli-engine,-eslint:glob-util,-eslint:config-file,-eslint:code-path
    - DEBUG_COLORS=false

