baseurl = "https://wmfs.github.io/"
languageCode = "en-us"
title = "Flobot Documentation"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-90924394-1"

[params]
	# General information
	author = "Tim Needham"
	description = "A low-code development framework for Node.js"
	copyright = "MIT"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/wmfs/flobot"

	version = "0.0.4"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "red"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = "flobotJS"
	github  = "wmfs/flobot"


[[menu.main]]
	name   = "Welcome!"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Key Concepts"
	url    = "key-concepts/"
	weight = 10

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 20

[[menu.main]]
	name   = "Core components"
	url    = "core-components/"
	weight = 30

[[menu.main]]
    name   = "License"
    url    = "license/"
    weight = 40


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
